import { useState } from 'react'
import { GEMINI_IMAGE_MODELS, GEMINI_TEXT_MODELS } from '../data/geminiModels'
import { GROK_IMAGE_MODELS, GROK_TEXT_MODELS } from '../data/grokModels'
import type { Provider, ProviderSettings } from '../lib/imageProvider'

interface Props {
  settings: ProviderSettings
  onChange: (patch: Partial<ProviderSettings>) => void
}

const PROVIDERS: Array<{ id: Provider; label: string }> = [
  { id: 'gemini', label: 'Google Gemini' },
  { id: 'grok', label: 'xAI Grok' },
]

export function ApiKeyInput({ settings, onChange }: Props) {
  const [reveal, setReveal] = useState(false)
  const isGrok = settings.provider === 'grok'
  const selectedGemini = GEMINI_IMAGE_MODELS.find((m) => m.id === settings.geminiModelId)

  const imageModels = isGrok ? GROK_IMAGE_MODELS : GEMINI_IMAGE_MODELS
  const textModels = isGrok ? GROK_TEXT_MODELS : GEMINI_TEXT_MODELS
  const key = isGrok ? settings.xaiKey : settings.apiKey
  const imageModelId = isGrok ? settings.grokModelId : settings.geminiModelId
  const textModelId = isGrok ? settings.grokTextModelId : settings.geminiTextModelId

  return (
    <section className="card">
      <h2>1. Connect your image AI</h2>
      <div className="chip-row small">
        {PROVIDERS.map((p) => (
          <button
            key={p.id}
            type="button"
            className={`chip outline ${settings.provider === p.id ? 'selected' : ''}`}
            onClick={() => onChange({ provider: p.id })}
          >
            {p.label}
          </button>
        ))}
      </div>

      {isGrok ? (
        <p className="hint">
          Wrap art is generated by xAI's Grok Imagine models. Get a key at{' '}
          <a href="https://console.x.ai" target="_blank" rel="noreferrer">
            console.x.ai
          </a>{' '}
          — Grok has no free tier, so add credits first (roughly $0.05–0.07 per image). The key is stored in your
          browser and relayed to xAI through this app's own server, which forwards it with each request and never
          saves or logs it.
        </p>
      ) : (
        <p className="hint">
          Wrap art is generated by Google's Gemini image models. Get a key at{' '}
          <a href="https://aistudio.google.com/apikey" target="_blank" rel="noreferrer">
            aistudio.google.com/apikey
          </a>{' '}
          — image generation needs billing enabled on the key's Google Cloud project (roughly $0.03–0.15 per
          image). The key stays in your browser's local storage and is only sent directly to Google's API — never to any
          server of ours. Avoid deploying this app publicly with your key exposed.
        </p>
      )}

      <div className="row">
        <label className="field">
          <span>{isGrok ? 'xAI API key' : 'Gemini API key'}</span>
          <div className="key-input">
            <input
              type={reveal ? 'text' : 'password'}
              value={key}
              onChange={(e) => onChange(isGrok ? { xaiKey: e.target.value } : { apiKey: e.target.value })}
              placeholder={isGrok ? 'xai-...' : 'AIza...'}
              autoComplete="off"
            />
            <button type="button" className="ghost-btn" onClick={() => setReveal((r) => !r)}>
              {reveal ? 'Hide' : 'Show'}
            </button>
          </div>
        </label>
        <label className="field">
          <span>Model</span>
          <select
            value={imageModelId}
            onChange={(e) =>
              onChange(isGrok ? { grokModelId: e.target.value } : { geminiModelId: e.target.value })
            }
          >
            {imageModels.map((m) => (
              <option key={m.id} value={m.id} title={m.description}>
                {m.label}
              </option>
            ))}
          </select>
          {!isGrok && selectedGemini?.note && <span className="model-note">⚠ {selectedGemini.note}</span>}
        </label>
        <label className="field">
          <span>Concept model (AI Wrap Generation)</span>
          <select
            value={textModelId}
            onChange={(e) =>
              onChange(isGrok ? { grokTextModelId: e.target.value } : { geminiTextModelId: e.target.value })
            }
          >
            {textModels.map((m) => (
              <option key={m.id} value={m.id} title={m.description}>
                {m.label}
              </option>
            ))}
          </select>
        </label>
      </div>
    </section>
  )
}
